// Frontend/pages/index.vue
﻿<script setup>
</script>
<template>
    <div>
        <main class="mx-auto max-w-6xl px-4 sm:px-6">
            <h1 class="text-center mt-24 leading-tight text-5xl md:leading-tight md:text-6xl font-bold">
                Rent with <em class="not-italic text-orange-500 relative">Confidence
                <svg
                        aria-hidden="true"
                        viewBox="0 0 418 42"
                        class="absolute left-0 top-2/3 h-8 w-full fill-orange-300/70"
                        preserveAspectRatio="none">
                    <path
                            d="M203.371.916c-26.013-2.078-76.686 1.963-124.73 9.946L67.3 12.749C35.421 18.062 18.2 21.766 6.004 25.934 1.244 27.561.828 27.778.874 28.61c.07 1.214.828 1.121 9.595-1.176 9.072-2.377 17.15-3.92 39.246-7.496C123.565 7.986 157.869 4.492 195.942 5.046c7.461.108 19.25 1.696 19.17 2.582-.107 1.183-7.874 4.31-25.75 10.366-21.992 7.45-35.43 12.534-36.701 13.884-2.173 2.308-.202 4.407 4.442 4.734 2.654.187 3.263.157 15.593-.78 35.401-2.686 57.944-3.488 88.365-3.143 46.327.526 75.721 2.23 130.788 7.584 19.787 1.924 20.814 1.98 24.557 1.332l.066-.011c1.201-.203 1.53-1.825.399-2.335-2.911-1.31-4.893-1.604-22.048-3.261-57.509-5.556-87.871-7.36-132.059-7.842-23.239-.254-33.617-.116-50.627.674-11.629.54-42.371 2.494-46.696 2.967-2.359.259 8.133-3.625 26.504-9.81 23.239-7.825 27.934-10.149 28.304-14.005.417-4.348-3.529-6-16.878-7.066Z"></path>
                </svg>
            </em> with Sigma&nbsp;Cars
            </h1>
            <div class="flex justify-center mt-24">
                <SearchCarsForm/>
            </div>
        </main>
        <div class="bg-slate-800 px-4 py-24 mt-24 mb-8 space-y-16">
            <p class="text-justify text-white text-xl leading-relaxed max-w-6xl mx-auto">
                At Sigma Cars, we are passionate about helping you explore the world on your terms. With our
                extensive fleet of high-quality vehicles, you can rest assured that you will find the perfect
                car, whether you are embarking on a cross-country adventure or need a reliable vehicle for
                your daily commute.
            </p>
        </div>
    </div>
</template>

// Frontend/pages/index.tsx
export default function Home() {
    return (
        <>
            <header className="flex bg-orange-600 p-2 sm:p-4 justify-between items-center text-white">
                <div className="flex gap-2 text-xl sm:text-2xl font-bold">
                    <div className="bg-slate-800 w-8 h-8 grid place-items-center rounded-md">
                        &Sigma;
                    </div>
                    <div className="leading-8">
                        Sigma Cars
                    </div>
                </div>
                <div className="flex-row font-normal text-lg sm:text-xl divide-x-2">
                    <a href="/" className="px-2">
                        Log in
                    </a>
                    <a href="/" className="px-2">
                        Sign up
                    </a>
                </div>
            </header>
            <main className="mx-auto max-w-4xl mt-40 p-3">
                <h1 className="text-center text-5xl md:text-6xl font-semibold">
                    Rent with Confidence with Sigma&nbsp;Cars
                </h1>
                <div className="flex justify-center mt-16">
                    <div className="flex flex-row">
                        <div className="basis-2 flex flex-col gap-2">
                            <label
                                className="ml-4 text-lg"
                                htmlFor="from">
                                From:
                            </label>
                            <input
                                className="bg-transparent block p-4 rounded-l-lg border"
                                type="text" id="from"/>
                        </div>
                        <div className="basis-2 flex flex-col gap-2">
                            <label
                                className="ml-4 text-lg"
                                htmlFor="to">
                                To:
                            </label>
                            <input
                                className="bg-transparent block p-4 border-y"
                                type="text" id="to"/>
                        </div>
                        <div className="basis-1 flex items-end">
                            <input
                                className="bg-slate-800 hover:bg-slate-700 block p-4 rounded-r-lg border-slate-800 hover:border-slate-700 border text-white"
                                type="submit" value="Explore!"/>
                        </div>
                    </div>
                </div>
                <h2 className="text-center mt-16 text-xl text-neutral-800">
                    <p className="text-justify">
                        At Sigma Cars, we are passionate about helping you explore the world on your terms. With our
                        extensive fleet of high-quality vehicles, you can rest assured that you will find the perfect
                        car, whether you are embarking on a cross-country adventure or need a reliable vehicle for
                        your daily commute.
                    </p>
                    <p className="mt-10 text-neutral-400 text-base">
                        Website is under development. Stay tuned for updates! Check out source code on&nbsp;
                        <a href="https://github.com/kacperwyczawski/sigma-cars" rel="noopener noreferrer"
                           className="text-blue-400 hover:underline">
                            GitHub
                        </a>
                    </p>
                </h2>
            </main>
        </>
    )
}
